### ISSUE TITLE
IPO

### ISSUE THREAD

**Issue by rslruiz** [jonzzki16/plBlueProject#2]
None

**Comment by jonzzki16** [comment]
> None

Sir, my apologies for not attending the class today. I have sore-eyes and I cannot stare at the screen as it hurts staying longer than 5 minutes.

**Comment by jonzzki16** [comment]
Sir, the attached links for our BlueTeam IPO-contacts. Thank you po.

https://docs.google.com/document/d/1pgc2Tw1ETwho7Qn7_ZFssaoodBcTaF1QZM74BAA8OUc/edit?usp=drivesdk

**Comment by jonzzki16** [comment]
Uploaded, Sir. Thank you!
